# Generated by Django 5.1.7 on 2025-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersMd", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
