# Generated by Django 5.1.7 on 2025-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersMd", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="about",
            field=models.CharField(max_length=255),
        ),
    ]
